# Site settings
title: HTML / CSS Winter '15
email: sandor@starterleague.com
description: Dashboard for the Starter League HTML / CSS class.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tsl-html-css.github.io" # the base hostname & protocol for your site
twitter_username: santheo
github_username:  santheo

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from
